import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("Concatenating")
arr3=np.concatenate((arr1,arr2))
print(arr3)
print("Vertical Stacking")
print(np.vstack((arr1,arr2)))
print("Horizontal Stacking")
print(np.hstack((arr1,arr2)))
